# Generated by Django 4.1.1 on 2022-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fingerprints", "0004_alter_fingerprint_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fingerprint",
            name="binary",
        ),
        migrations.RemoveField(
            model_name="fingerprint",
            name="file",
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="fingerprint_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Fingerprint ID"
            ),
        ),
    ]
