# Generated by Django 4.1.1 on 2022-09-29 03:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_exam_active"),
        (
            "fingerprints",
            "0005_remove_fingerprint_binary_remove_fingerprint_file_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FingerprintVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("state", models.BooleanField(verbose_name="Created")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
