# Generated by Django 4.1.1 on 2022-09-26 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=100, verbose_name="Course Name"),
                ),
                (
                    "course_code",
                    models.CharField(max_length=10, verbose_name="Course Code"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                        ],
                        default="100",
                        max_length=3,
                        verbose_name="Level",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Start Date and Time")),
                ("end", models.DateTimeField(verbose_name="End Date and Time")),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Programme Name"),
                ),
                ("college", models.CharField(max_length=100, verbose_name="College")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "other_names",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Other Names",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Student ID Number"
                    ),
                ),
                (
                    "index_number",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Student Index Number"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                        ],
                        default="100",
                        max_length=3,
                        verbose_name="Level of Student",
                    ),
                ),
                (
                    "programme_of_study",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        related_query_name="student",
                        to="students.programme",
                    ),
                ),
                (
                    "registered_exams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        related_query_name="student",
                        to="students.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Name")),
                ("capacity", models.IntegerField(verbose_name="Room Capacity")),
                (
                    "invigilators",
                    models.ManyToManyField(
                        limit_choices_to={"invigilator": True},
                        related_name="assigned_exams",
                        related_query_name="assigned_exam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="allocated_rooms",
                        related_query_name="allocated_room",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="rooms",
            field=models.ManyToManyField(to="students.room"),
        ),
    ]
