# Generated by Django 4.1.1 on 2022-09-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("fingerprints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fingerprint",
            name="student",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fingerprint",
                to="students.student",
                verbose_name="Fingerprint",
            ),
            preserve_default=False,
        ),
    ]
