# Generated by Django 4.1.1 on 2022-09-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fingerprints", "0003_remove_fingerprint_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fingerprint",
            options={"ordering": ("-created",)},
        ),
    ]
