# Generated by Django 4.1.1 on 2022-09-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
    ]
