# Generated by Django 4.1.1 on 2022-09-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examattendance",
            options={"ordering": ("-created",)},
        ),
    ]
